name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  pypi-build:
    name: build artifacts for PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      # NOTE: the Poetry venv is created during this step
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Build wheels and sdist with Poetry
        run: poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist
          compression-level: 0 # all dist files are already compressed

  pypi-publish:
    name: upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - pypi-build
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: ${{ github.workspace }}/dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
